root: ./

navigation:
  - title: 'Linux'
    icon: 'linux'
    description: ''
    pages:
      - title: 'Install Zapret'
        icon: 'code'
        path: ./linux/install-zapret.md

  - title: 'Windows'
    icon: 'windows'
    description: ''
    pages:
      - title: 'Install GoodbyeDPI'
        icon: 'code'
        path: ./windows/install-goodbyedpi.md